# 라이브러리 선언

In [3]:
# pandas
# 데이터 처리 관련 라이브러리
import pandas as pd

# numpy
# 수와 관련된 계산 라이브러리
import numpy as np

# 1. 데이터 불러오기

In [4]:
# 데이터 불러오기
customerData = pd.read_csv("../dataset/customerdata.csv")

# 데이터 저장하기
customerData.to_csv("./outdata.csv", index=False)

In [5]:
# 고객의 PAINPOINT..
customerData.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CUSTID       150 non-null    str
 1   AVGPRICE     150 non-null    float64
 2   EMI          150 non-null    int64
 3   DEVICECOUNT  150 non-null    int64
 4   PRODUCTAGE   150 non-null    float64
 5   CUSTTYPE     150 non-null    str
dtypes: float64(2), int64(2), str(2)
memory usage: 7.2 KB

In [6]:
# 고객의 PAINPOINT..
customerData.describe()

          AVGPRICE         EMI  DEVICECOUNT  PRODUCTAGE
count   150.000000  150.000000   150.000000  150.000000
mean   3432.741108    2.053333     4.973333    1.932601
std     371.571877    0.445510     0.996279    0.807457
min    2390.083736    1.000000     3.000000    0.800000
25%    3214.543122    2.000000     4.000000    1.000000
50%    3408.300000    2.000000     5.000000    2.077000
75%    3664.767001    2.000000     6.000000    2.574525
max    4296.873743    3.000000     6.000000    3.483573

# 1. 데이터 행 조회하기

In [7]:
customerData.head(2)

   CUSTID    AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.90000    3            6    1.679181  Big-Screen-lover
1  A14219  3642.44195    2            4    2.682023      Sleeping-dog

In [8]:
targetEmi = 3
emi3Data = customerData.loc[customerData.EMI == targetEmi]
customerData.shape

(150, 6)

In [9]:
targetEmi = 3
targetPrice = 3000

# 무이자 할부가 3건 이면서 평균 구매 가격이 3000 이상인 고객만 조회
resultData = customerData.loc[(customerData.EMI == targetEmi) & (customerData.AVGPRICE >= targetPrice)]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
27   F17131  3179.708359    3            6    1.100000        Early-bird
33   G16437  3787.328898    3            6    1.000000        Early-bird
36   G18402  3402.199381    3            6    1.000000        Early-bird
40   H16326  3988.935304    3            6    0.900000        Early-bird
45   I12899  3018.895637    3            6    0.900000        Early-bird
51   J10809  3676.135627    3            6    0.800000        Early-bird
53   J16445  3041.848186    3            6    0.800000        Early-bird
60   L13892  3263.515145    3            6    1.100000        Early-bird
67   N13273  3839.694732    3            6    1.100000        Early-bird
95   R16364  3592.353540    3            6    0.900000        Early-bird
107  S17396  3895.200000    3            6    2.055707  Big-Screen-lover
113  T11473  4165.700000    3            6    1.780674  Big-Screen-lover
126  V18566  3527.701867    3            6    0.900000        Early-bird
130  W13404  4296.873743    3            6    1.100000        Early-bird
142  Z11525  3259.018704    3            6    0.900000        Early-bird
146  Z13534  3662.437527    3            6    0.900000        Early-bird

In [10]:
## 특정 컬럼에 대한 다중 값 도회 시 isin
## 해당 부정 표현 NOT IN isin 조건 잎에 ~를 붙여주면 된다
targetEmiList = [1,3]

resultData = customerData.loc[(~customerData.EMI.isin(targetEmiList))]
resultData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog
3    A16605  3713.211107    2            6    0.900000        Early-bird
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog
5    B16849  3755.263391    2            4    2.786665      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
144  Z12772  3029.600000    2            4    2.093035  Big-Screen-lover
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183    2            6    1.200000        Early-bird

[120 rows x 6 columns]

## 데이터 타입 변환

In [11]:
# 데이터 타입 확인
customerData.dtypes

# EMI 컬럼 INT -> FLOAT
customerData['EMI'] = customerData.EMI.astype(float)
customerData

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover
1    A14219  3642.441950  2.0            4    2.682023      Sleeping-dog
2    A15312  3653.884565  2.0            5    3.208202      Sleeping-dog
3    A16605  3713.211107  2.0            6    0.900000        Early-bird
4    B10634  3391.074215  2.0            4    2.453656      Sleeping-dog
..      ...          ...  ...          ...         ...               ...
145  Z13253  3678.800000  2.0            5    2.463670  Big-Screen-lover
146  Z13534  3662.437527  3.0            6    0.900000        Early-bird
147  Z16428  3516.500000  2.0            5    2.371301  Big-Screen-lover
148  Z16735  3300.100000  2.0            5    1.704942  Big-Screen-lover
149  Z19835  3326.526183  2.0            6    1.200000        Early-bird

[150 rows x 6 columns]

In [12]:
# 인덱스로도 조회가 가능하다
targetIndex = [0,1,3]
customerData.loc[targetIndex]

   CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0  A13566  4273.900000  3.0            6    1.679181  Big-Screen-lover
1  A14219  3642.441950  2.0            4    2.682023      Sleeping-dog
3  A16605  3713.211107  2.0            6    0.900000        Early-bird

# 2. 데이터 컬럼 조회

In [13]:
# 인덱스 컬럼을 조회하기
customerData.iloc[:, [0, 2 ,3]]

     CUSTID  EMI  DEVICECOUNT
0    A13566  3.0            6
1    A14219  2.0            4
2    A15312  2.0            5
3    A16605  2.0            6
4    B10634  2.0            4
..      ...  ...          ...
145  Z13253  2.0            5
146  Z13534  3.0            6
147  Z16428  2.0            5
148  Z16735  2.0            5
149  Z19835  2.0            6

[150 rows x 3 columns]

In [14]:
# EMI 유형이 2보다 크고 선택 컬럼[CUSTID, AVGPRICE, EMI]
targetColumn = ["CUSTID", "AVGPRICE", "EMI"]
emi3CsData = customerData.loc[customerData.EMI > 2, targetColumn]
emi3OverData = emi3CsData.reset_index(drop=True)
emi3OverData

    CUSTID     AVGPRICE  EMI
0   A13566  4273.900000  3.0
1   F17131  3179.708359  3.0
2   G16437  3787.328898  3.0
3   G18402  3402.199381  3.0
4   H16326  3988.935304  3.0
5   I12899  3018.895637  3.0
6   J10809  3676.135627  3.0
7   J15083  2811.265932  3.0
8   J16445  3041.848186  3.0
9   L13892  3263.515145  3.0
10  N13273  3839.694732  3.0
11  R16364  3592.353540  3.0
12  S17396  3895.200000  3.0
13  T11473  4165.700000  3.0
14  V18566  3527.701867  3.0
15  W13404  4296.873743  3.0
16  X13390  2947.543982  3.0
17  Z11525  3259.018704  3.0
18  Z13534  3662.437527  3.0

# 3. 데이터 조작하기 (DB: CASE WHEN)

In [15]:
customerData["PRODUCTAGE_NEW"] = \
    np.where(customerData.PRODUCTAGE < 1, 1, customerData.PRODUCTAGE)

# 본인이 작성한 코드에 대한 검증 로직
# customerData.loc[ (customerData.PRODUCTAGE < 1) & (customerData.PRODUCTAGE_NEW != 1)]

customerData.loc[ (customerData.PRODUCTAGE >= 1) & (customerData.PRODUCTAGE_NEW != 1)]

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW
0,A13566,4273.900000,3.0,6,1.679181,Big-Screen-lover,1.679181
1,A14219,3642.441950,2.0,4,2.682023,Sleeping-dog,2.682023
2,A15312,3653.884565,2.0,5,3.208202,Sleeping-dog,3.208202
4,B10634,3391.074215,2.0,4,2.453656,Sleeping-dog,2.453656
5,B16849,3755.263391,2.0,4,2.786665,Sleeping-dog,2.786665
...,...,...,...,...,...,...,...
144,Z12772,3029.600000,2.0,4,2.093035,Big-Screen-lover,2.093035
145,Z13253,3678.800000,2.0,5,2.463670,Big-Screen-lover,2.463670
147,Z16428,3516.500000,2.0,5,2.371301,Big-Screen-lover,2.371301
148,Z16735,3300.100000,2.0,5,1.704942,Big-Screen-lover,1.704942
149,Z19835,3326.526183,2.0,6,1.200000,Early-bird,1.200000

In [16]:
customerData["PRODUCTAGE_NEW"] = \
    np.where(customerData.PRODUCTAGE < 1, 1, 
             np.where(customerData.PRODUCTAGE < 2, 2,
                      np.where(customerData.PRODUCTAGE < 3, 3, customerData.PRODUCTAGE)))

In [17]:
### 데이터 조작 pandas
### 사용하는 방법이 시점마다 다르기 때문에 ai는 람다 방식을 많이 사용한다 하지만 실제로는 현장에서는 잘 사용하지 않는다
### 1. np.where: 간단한 데이터 처리 시
### 2. loc: 딱 수정 포인트만 조건으로 검색해서 수정하고 빠지기
### 3. function: 복잡한 로직인 경우 함수를 정의해서 처리
### 4. dictionary 활용: 딕셔너리 정의 후 매핑: 문자 -> 숫자 변환
### 5. labelEncoder 활용: 카테고리 데이터를 숫자로 매핑( 근데 카테고리가 많은 경우)
### 6. onehotEncoder 활용: 인공지능에서 이미지 학습 1 -> 00001

In [18]:
avgPriceMean = customerData.AVGPRICE.mean()
avgPriceMean

np.float64(3432.7411077064326)

In [19]:
%%timeit

### np.where 활용 방법: 데이터프레임["컬럼명"] = np.where(조건, 참일때 값, 거짓일때 값)
customerData["NEW_CAT"] = np.where(customerData.AVGPRICE < avgPriceMean, 0, 1)
customerData.loc[(customerData.NEW_CAT < 1) & (customerData.AVGPRICE >= avgPriceMean)]

304 μs ± 8.59 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [20]:
%%timeit

### loc 기능 (평균 가격보다 작게 구매 금액이 형성되어 있으면 -> 0)
customerData.loc[customerData.AVGPRICE < avgPriceMean, "NEW_CAT2"] = 0
customerData.loc[customerData.AVGPRICE >= avgPriceMean, "NEW_CAT2"] = 1

267 μs ± 18.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [21]:
customerData.loc[customerData.NEW_CAT != customerData.NEW_CAT2]

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE, PRODUCTAGE_NEW, NEW_CAT, NEW_CAT2]
Index: []

In [22]:
### 3번째 로직을 특정 컬럼에 대해서 fastapi 호출도 해야하고 복잡하게 해야 할 때

def custCategory(inValue):
    ### avgPriceMean: 고객들의 평균 구매 가격
    # 각 고객들의 AVGPRICE 값
    # inValue = 4000
    # 리턴 Value
    outValue = 0
    
    # 각 고객들의 AVGPRICE가 전체 고객의 평균 AVGPRICE보다 작으면 0 아니면 1
    if inValue < avgPriceMean:
        outValue = 0
    else:
        outValue = 1
    return outValue

In [23]:
customerData["NEW_CAT3"] = customerData.AVGPRICE.apply(custCategory)

In [24]:
customerData.loc[(customerData.NEW_CAT2 != customerData.NEW_CAT3)]

Empty DataFrame
Columns: [CUSTID, AVGPRICE, EMI, DEVICECOUNT, PRODUCTAGE, CUSTTYPE, PRODUCTAGE_NEW, NEW_CAT, NEW_CAT2, NEW_CAT3]
Index: []

# 컬럼간 데이터 연산하기

In [25]:
customerData["EMI_DEVCOUNT"] = customerData.EMI * customerData.DEVICECOUNT
# customerData.CUSTID[0] +  "_" + customerData.AVGPRICE 이거는 안됨
customerData.CUSTID.str[0] + "_" + customerData.AVGPRICE.astype(str)
customerData.CUSTID.str[1:].astype(int) + customerData.AVGPRICE
customerData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW,NEW_CAT,NEW_CAT2,NEW_CAT3,EMI_DEVCOUNT
0,A13566,4273.900000,3.0,6,1.679181,Big-Screen-lover,2.000000,1,1.0,1,18.0
1,A14219,3642.441950,2.0,4,2.682023,Sleeping-dog,3.000000,1,1.0,1,8.0
2,A15312,3653.884565,2.0,5,3.208202,Sleeping-dog,3.208202,1,1.0,1,10.0
3,A16605,3713.211107,2.0,6,0.900000,Early-bird,1.000000,1,1.0,1,12.0
4,B10634,3391.074215,2.0,4,2.453656,Sleeping-dog,3.000000,0,0.0,0,8.0
...,...,...,...,...,...,...,...,...,...,...,...
145,Z13253,3678.800000,2.0,5,2.463670,Big-Screen-lover,3.000000,1,1.0,1,10.0
146,Z13534,3662.437527,3.0,6,0.900000,Early-bird,1.000000,1,1.0,1,18.0
147,Z16428,3516.500000,2.0,5,2.371301,Big-Screen-lover,3.000000,1,1.0,1,10.0
148,Z16735,3300.100000,2.0,5,1.704942,Big-Screen-lover,2.000000,0,0.0,0,10.0
149,Z19835,3326.526183,2.0,6,1.200000,Early-bird,2.000000,0,0.0,0,12.0

# 4. 정렬하기

In [36]:
# 정렬하기
sortKey = ["EMI", "AVGPRICE"]
customerData.sort_values( by = sortKey, ascending = [True, False] )
customerData

,CUSTID,AVGPRICE,EMI,DEVICECOUNT,PRODUCTAGE,CUSTTYPE,PRODUCTAGE_NEW,NEW_CAT,NEW_CAT2,NEW_CAT3,EMI_DEVCOUNT
0,A13566,4273.900000,3.0,6,1.679181,Big-Screen-lover,2.000000,1,1.0,1,18.0
1,A14219,3642.441950,2.0,4,2.682023,Sleeping-dog,3.000000,1,1.0,1,8.0
2,A15312,3653.884565,2.0,5,3.208202,Sleeping-dog,3.208202,1,1.0,1,10.0
3,A16605,3713.211107,2.0,6,0.900000,Early-bird,1.000000,1,1.0,1,12.0
4,B10634,3391.074215,2.0,4,2.453656,Sleeping-dog,3.000000,0,0.0,0,8.0
...,...,...,...,...,...,...,...,...,...,...,...
145,Z13253,3678.800000,2.0,5,2.463670,Big-Screen-lover,3.000000,1,1.0,1,10.0
146,Z13534,3662.437527,3.0,6,0.900000,Early-bird,1.000000,1,1.0,1,18.0
147,Z16428,3516.500000,2.0,5,2.371301,Big-Screen-lover,3.000000,1,1.0,1,10.0
148,Z16735,3300.100000,2.0,5,1.704942,Big-Screen-lover,2.000000,0,0.0,0,10.0
149,Z19835,3326.526183,2.0,6,1.200000,Early-bird,2.000000,0,0.0,0,12.0

# 5. 그룹바이

In [37]:
groupKey = ["EMI"]

In [38]:
customerData.groupby(by=groupKey)["AVGPRICE"].agg(["mean"])

            mean
EMI
1.0  3119.031810
2.0  3441.429664
3.0  3559.487188

In [41]:
# 고객 타입별로 PRODUCTAGE의 평균을 찍어 보고 싶다
groupKey = ["CUSTTYPE"]
customerData.groupby(by=groupKey)["PRODUCTAGE"].agg(["mean", "max", "min", "std", "sum", "count"]).reset_index()

           CUSTTYPE      mean       max       min       std         sum  count
0  Big-Screen-lover  2.193531  3.367229  1.498896  0.445798  109.676567     50
1        Early-bird  0.946000  1.300000  0.800000  0.105386   47.300000     50
2      Sleeping-dog  2.658271  3.483573  1.865857  0.415534  132.913529     50